/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StopwatchRouteImport } from './routes/stopwatch'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RunRouteImport } from './routes/run'
import { Route as RoutinesRouteImport } from './routes/routines'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TimerIdRouteImport } from './routes/timer.$id'
import { Route as EditorIdRouteImport } from './routes/editor.$id'

const StopwatchRoute = StopwatchRouteImport.update({
  id: '/stopwatch',
  path: '/stopwatch',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RunRoute = RunRouteImport.update({
  id: '/run',
  path: '/run',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutinesRoute = RoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimerIdRoute = TimerIdRouteImport.update({
  id: '/timer/$id',
  path: '/timer/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorIdRoute = EditorIdRouteImport.update({
  id: '/editor/$id',
  path: '/editor/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/routines': typeof RoutinesRoute
  '/run': typeof RunRoute
  '/settings': typeof SettingsRoute
  '/stopwatch': typeof StopwatchRoute
  '/editor/$id': typeof EditorIdRoute
  '/timer/$id': typeof TimerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/routines': typeof RoutinesRoute
  '/run': typeof RunRoute
  '/settings': typeof SettingsRoute
  '/stopwatch': typeof StopwatchRoute
  '/editor/$id': typeof EditorIdRoute
  '/timer/$id': typeof TimerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/routines': typeof RoutinesRoute
  '/run': typeof RunRoute
  '/settings': typeof SettingsRoute
  '/stopwatch': typeof StopwatchRoute
  '/editor/$id': typeof EditorIdRoute
  '/timer/$id': typeof TimerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/routines'
    | '/run'
    | '/settings'
    | '/stopwatch'
    | '/editor/$id'
    | '/timer/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/routines'
    | '/run'
    | '/settings'
    | '/stopwatch'
    | '/editor/$id'
    | '/timer/$id'
  id:
    | '__root__'
    | '/'
    | '/routines'
    | '/run'
    | '/settings'
    | '/stopwatch'
    | '/editor/$id'
    | '/timer/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RoutinesRoute: typeof RoutinesRoute
  RunRoute: typeof RunRoute
  SettingsRoute: typeof SettingsRoute
  StopwatchRoute: typeof StopwatchRoute
  EditorIdRoute: typeof EditorIdRoute
  TimerIdRoute: typeof TimerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stopwatch': {
      id: '/stopwatch'
      path: '/stopwatch'
      fullPath: '/stopwatch'
      preLoaderRoute: typeof StopwatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/run': {
      id: '/run'
      path: '/run'
      fullPath: '/run'
      preLoaderRoute: typeof RunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routines': {
      id: '/routines'
      path: '/routines'
      fullPath: '/routines'
      preLoaderRoute: typeof RoutinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timer/$id': {
      id: '/timer/$id'
      path: '/timer/$id'
      fullPath: '/timer/$id'
      preLoaderRoute: typeof TimerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$id': {
      id: '/editor/$id'
      path: '/editor/$id'
      fullPath: '/editor/$id'
      preLoaderRoute: typeof EditorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RoutinesRoute: RoutinesRoute,
  RunRoute: RunRoute,
  SettingsRoute: SettingsRoute,
  StopwatchRoute: StopwatchRoute,
  EditorIdRoute: EditorIdRoute,
  TimerIdRoute: TimerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
